kind: Kustomization

resources:
- install.yaml

patches:
- path: envoy_gateway_patch.yaml

images:
- name: envoyproxy/gateway
  newName: aibrix-cn-beijing.cr.volces.com/aibrix/gateway
  newTag: v1.2.8